=== zyllio/scorm-content/contents/securité-incendie/imscp_v1p1.xsd
<?xml version = "1.0" encoding = "UTF-8"?><!--Generated by Turbo XML 2.3.1.100. Conforms to w3c http://www.w3.org/2001/XMLSchema--><xsd:schema xmlns = "http://www.imsglobal.org/xsd/imscp_v1p1" targetNamespace = "http://www.imsglobal.org/xsd/imscp_v1p1" xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd = "http://www.w3.org/2001/XMLSchema" version = "IMS CP 1.1.4" elementFormDefault = "qualified"><xsd:import namespace = "http://www.w3.org/XML/1998/namespace" schemaLocation = "http://www.w3.org/2001/xml.xsd"/><xsd:attributeGroup name = "attr.base"><xsd:attribute ref = "xml:base"/></xsd:attributeGroup><xsd:attributeGroup name = "attr.default"><xsd:attribute name = "default" type = "xsd:IDREF"/></xsd:attributeGroup><xsd:attributeGroup name = "attr.href"><xsd:attribute name = "href" type = "xsd:anyURI"/></xsd:attributeGroup><xsd:attributeGroup name = "attr.href.req"><xsd:attribute name = "href" use = "required" type = "xsd:anyURI"/></xsd:attributeGroup><xsd:attributeGroup name = "attr.identifier.req"><xsd:attribute name = "identifier" use = "required" type = "xsd:ID"/></xsd:attributeGroup><xsd:attributeGroup name = "attr.identifier"><xsd:attribute name = "identifier" type = "xsd:ID"/></xsd:attributeGroup><xsd:attributeGroup name = "attr.isvisible"><xsd:attribute name = "isvisible" type = "xsd:boolean"/></xsd:attributeGroup><xsd:attributeGroup name = "attr.parameters"><xsd:attribute name = "parameters" type = "xsd:string"/></xsd:attributeGroup><xsd:attributeGroup name = "attr.identifierref"><xsd:attribute name = "identifierref" type = "xsd:string"/></xsd:attributeGroup><xsd:attributeGroup name = "attr.identifierref.req"><xsd:attribute name = "identifierref" use = "required" type = "xsd:string"/></xsd:attributeGroup><xsd:attributeGroup name = "attr.resourcetype.req"><xsd:attribute name = "type" use = "required" type = "xsd:string"/></xsd:attributeGroup><xsd:attributeGroup name = "attr.structure.req"><xsd:attribute name = "structure" default = "hierarchical" type = "xsd:string"/></xsd:attributeGroup><xsd:attributeGroup name = "attr.version"><xsd:attribute name = "version" type = "xsd:string"/></xsd:attributeGroup><xsd:group name = "grp.any"><xsd:sequence><xsd:any namespace = "##other" processContents = "lax" minOccurs = "0" maxOccurs = "unbounded"/></xsd:sequence></xsd:group><xsd:element name = "dependency" type = "dependencyType"/><xsd:element name = "file" type = "fileType"/><xsd:element name = "item" type = "itemType"/><xsd:element name = "manifest" type = "manifestType"/><xsd:element name = "metadata" type = "metadataType"/><xsd:element name = "organization" type = "organizationType"/><xsd:element name = "organizations" type = "organizationsType"/><xsd:element name = "resource" type = "resourceType"/><xsd:element name = "resources" type = "resourcesType"/><xsd:element name = "schema" type = "schemaType"/><xsd:element name = "schemaversion" type = "schemaversionType"/><xsd:element name = "title" type = "titleType"/><xsd:complexType name = "dependencyType"><xsd:sequence><xsd:group ref = "grp.any"/></xsd:sequence><xsd:attributeGroup ref = "attr.identifierref.req"/><xsd:anyAttribute namespace = "##other" processContents = "strict"/></xsd:complexType><xsd:complexType name = "fileType"><xsd:sequence><xsd:element ref = "metadata" minOccurs = "0"/><xsd:group ref = "grp.any"/></xsd:sequence><xsd:attributeGroup ref = "attr.href.req"/><xsd:anyAttribute namespace = "##other" processContents = "lax"/></xsd:complexType><xsd:complexType name = "itemType"><xsd:sequence><xsd:element ref = "title" minOccurs = "0"/><xsd:element ref = "item" minOccurs = "0" maxOccurs = "unbounded"/><xsd:element ref = "metadata" minOccurs = "0"/><xsd:group ref = "grp.any"/></xsd:sequence><xsd:attributeGroup ref = "attr.identifier.req"/><xsd:attributeGroup ref = "attr.identifierref"/><xsd:attributeGroup ref = "attr.isvisible"/><xsd:attributeGroup ref = "attr.parameters"/><xsd:anyAttribute namespace = "##other" processContents = "lax"/></xsd:complexType><xsd:complexType name = "manifestType"><xsd:sequence><xsd:element ref = "metadata" minOccurs = "0"/><xsd:element ref = "organizations"/><xsd:element ref = "resources"/><xsd:element ref = "manifest" minOccurs = "0" maxOccurs = "unbounded"/><xsd:group ref = "grp.any"/></xsd:sequence><xsd:attributeGroup ref = "attr.identifier.req"/><xsd:attributeGroup ref = "attr.version"/><xsd:attribute ref = "xml:base"/><xsd:anyAttribute namespace = "##other" processContents = "lax"/></xsd:complexType><xsd:complexType name = "metadataType"><xsd:sequence><xsd:element ref = "schema" minOccurs = "0"/><xsd:element ref = "schemaversion" minOccurs = "0"/><xsd:group ref = "grp.any"/></xsd:sequence><xsd:anyAttribute namespace = "##other" processContents = "lax"/></xsd:complexType><xsd:complexType name = "organizationsType"><xsd:sequence><xsd:element ref = "organization" minOccurs = "0" maxOccurs = "unbounded"/><xsd:group ref = "grp.any"/></xsd:sequence><xsd:attributeGroup ref = "attr.default"/><xsd:anyAttribute namespace = "##other" processContents = "lax"/></xsd:complexType><xsd:complexType name = "organizationType"><xsd:sequence><xsd:element ref = "title" minOccurs = "0"/><xsd:element ref = "item" maxOccurs = "unbounded"/><xsd:element ref = "metadata" minOccurs = "0"/><xsd:group ref = "grp.any"/></xsd:sequence><xsd:attributeGroup ref = "attr.identifier.req"/><xsd:attributeGroup ref = "attr.structure.req"/><xsd:anyAttribute namespace = "##other" processContents = "lax"/></xsd:complexType><xsd:complexType name = "resourcesType"><xsd:sequence><xsd:element ref = "resource" minOccurs = "0" maxOccurs = "unbounded"/><xsd:group ref = "grp.any"/></xsd:sequence><xsd:attributeGroup ref = "attr.base"/><xsd:anyAttribute namespace = "##other" processContents = "lax"/></xsd:complexType><xsd:complexType name = "resourceType"><xsd:sequence><xsd:element ref = "metadata" minOccurs = "0"/><xsd:element ref = "file" minOccurs = "0" maxOccurs = "unbounded"/><xsd:element ref = "dependency" minOccurs = "0" maxOccurs = "unbounded"/><xsd:group ref = "grp.any"/></xsd:sequence><xsd:attributeGroup ref = "attr.identifier.req"/><xsd:attributeGroup ref = "attr.resourcetype.req"/><xsd:attributeGroup ref = "attr.base"/><xsd:attributeGroup ref = "attr.href"/><xsd:anyAttribute namespace = "##other" processContents = "lax"/></xsd:complexType><xsd:simpleType name = "schemaType"><xsd:restriction base = "xsd:string"/></xsd:simpleType><xsd:simpleType name = "schemaversionType"><xsd:restriction base = "xsd:string"/></xsd:simpleType><xsd:simpleType name = "titleType"><xsd:restriction base = "xsd:string"/></xsd:simpleType></xsd:schema>

=== zyllio/scorm-content/rituels-manageriaux/imsmanifest.xml
<?xml version="1.0" standalone="no" ?>
<manifest identifier="A0pk58Cz5LQRYFr6tGkCUuBRyiMo8QFsGux8iRkl" version="1.3"
  xmlns="http://www.imsglobal.org/xsd/imscp_v1p1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_v1p3"
  xmlns:adlseq="http://www.adlnet.org/xsd/adlseq_v1p3"
  xmlns:imsss="http://www.imsglobal.org/xsd/imsss"
  xsi:schemaLocation="http://www.imsglobal.org/xsd/imscp_v1p1 imscp_v1p1.xsd
                      http://www.adlnet.org/xsd/adlcp_v1p3 adlcp_v1p3.xsd
                      http://www.adlnet.org/xsd/adlseq_v1p3 adlseq_v1p3.xsd
                      http://www.imsglobal.org/xsd/imsss imsss_v1p0.xsd">
  <metadata>
    <schema>ADL SCORM</schema>
    <schemaversion>2004 4th Edition</schemaversion>
    <adlcp:location>metadata.xml</adlcp:location>   
  </metadata>
  <organizations default="B0">
    <organization identifier="B0" adlseq:objectivesGlobalToSystem="false">
      <title>Les rituels managériaux</title>
      <item identifier="i1" identifierref="r1" isvisible="true">
        <title>Les rituels managériaux</title>
        <adlcp:dataFromLMS>eyJjcHYiOiJHdXg4aVJrbCIsInJsZCI6ZmFsc2V9</adlcp:dataFromLMS>
        <imsss:sequencing>
          <imsss:deliveryControls tracked="true" completionSetByContent="true" objectiveSetByContent="true"/>
        </imsss:sequencing>
      </item>
      <metadata>
        <adlcp:location>metadata.xml</adlcp:location>
      </metadata>
      <imsss:sequencing>
        <imsss:controlMode choice="true" flow="true"/>
      </imsss:sequencing>
    </organization>
  </organizations>
  <resources>
    <resource identifier="r1" type="webcontent" adlcp:scormType="sco" href="scormdriver/indexAPI.html">
      <!-- SCORMDRIVER STUFF -->
      <file href="scormdriver/indexAPI.html" />
      <file href="scormdriver/preloadIntegrity.js" />
      <file href="scormdriver/driverOptions.js" />
      <file href="scormdriver/AICCComm.html" />
      <file href="scormdriver/auto-scripts/AutoBookmark.js" />
      <file href="scormdriver/auto-scripts/AutoCompleteSCO.js" />
      <file href="scormdriver/auto-scripts/CourseExit.js" />
      <file href="scormdriver/blank.html" />
      <file href="scormdriver/goodbye.html" />
      <file href="scormdriver/scormdriver.js" />
      <file href="scormdriver/browsersniff.js" />

      <!-- RUNTIME COMMON STUFF -->
      <file href="scormcontent/index.html" />

      
        <file href="scormcontent/lib/fonts/icomoon.ttf"/>
        <file href="scormcontent/lib/fonts/icomoon.woff"/>

        <file href="scormcontent/lib/icomoon.css"/>
        <file href="scormcontent/lib/player-0.0.11.min.js"/>
        <file href="scormcontent/lib/lzwcompress.js"/>
      

      <!-- FRONTEND BUNDLE ASSETS -->
      <file href="scormcontent/lib/rise/5d5a7671.js" />
<file href="scormcontent/lib/rise/fa74d7f1.css" />
<file href="scormcontent/lib/rise/ede5dd04.js" />
<file href="scormcontent/lib/rise/1cf4b6e0.css" />
<file href="scormcontent/lib/rise/a41cfcfc.js" />
<file href="scormcontent/lib/rise/254e83dc.js" />
<file href="scormcontent/lib/rise/c82cca6a.js" />
<file href="scormcontent/lib/rise/40b4cf18.js" />
<file href="scormcontent/lib/rise/b2cebec4.js" />
<file href="scormcontent/lib/rise/70fd6e03.js" />
<file href="scormcontent/lib/rise/48ed4c70.js" />
<file href="scormcontent/lib/rise/0bcec83e.js" />
<file href="scormcontent/lib/rise/bd8404c0.js" />
<file href="scormcontent/lib/mondrian/entry.js" />
<file href="scormcontent/lib/mondrian/ab103845.js" />
<file href="scormcontent/lib/mondrian/1a68f054.js" />
<file href="scormcontent/lib/mondrian/03ab2a8e.js" />
<file href="scormcontent/lib/mondrian/daeabcf0.js" />
<file href="scormcontent/lib/mondrian/45d26a13.js" />
<file href="scormcontent/lib/mondrian/09e37aee.js" />
<file href="scormcontent/lib/mondrian/196251cf.js" />
<file href="scormcontent/lib/sandbox/sandbox.html" />
<file href="scormcontent/lib/sandbox/b8fc6988.js" />
<file href="scormcontent/lib/sandbox/4adfab46.css" />


      <!-- RUNTIME CONTENT STUFF -->
      <file href="scormcontent/lib/fonts/8sBAnRpjSwGhsiLb-arial-mt-italic.woff" />
<file href="scormcontent/lib/fonts/17LqU4XT4qjN8IJL-arial.woff" />
<file href="scormcontent/lib/fonts/Lato2-Regular.woff" />
<file href="scormcontent/lib/fonts/Lato2-Light.woff" />
<file href="scormcontent/lib/fonts/Lato2-Italic.woff" />
<file href="scormcontent/lib/fonts/Lato2-Bold.woff" />
<file href="scormcontent/lib/fonts/Lato2-Black.woff" />
<file href="scormcontent/lib/fonts/Merriweather-Black.woff" />
<file href="scormcontent/lib/fonts/Merriweather-Italic.woff" />
<file href="scormcontent/lib/fonts/Merriweather-Bold.woff" />
<file href="scormcontent/lib/fonts/Merriweather-Regular.woff" />
<file href="scormcontent/lib/fonts/Merriweather-Light.woff" />
<file href="scormcontent/assets/yQICpjDPJ0EmswfU.jpg" />
<file href="scormcontent/assets/rituels.png" />
<file href="scormcontent/assets/FR-rituel%20VF.mp4" />
<file href="scormcontent/assets/FR-rituel%20VF.png" />
<file href="scormcontent/assets/Engagement.png" />
<file href="scormcontent/assets/sens.png" />
<file href="scormcontent/assets/X-%C3%A9coute.png" />
<file href="scormcontent/assets/accompagnement.png" />
<file href="scormcontent/assets/D%C3%A9briefer.png" />
<file href="scormcontent/assets/quote_background.jpg" />
<file href="scormcontent/assets/Patrick%20Stassi.png" />
<file href="scormcontent/assets/rituels%20indiv.jpg" />
<file href="scormcontent/assets/Rituels%20int%C3%A9gration.png" />
<file href="scormcontent/assets/rituel%20505.png" />
<file href="scormcontent/assets/rituel%20EDO.png" />
<file href="scormcontent/assets/rituel%20ED.png" />
<file href="scormcontent/assets/REMU2.png" />
<file href="scormcontent/assets/TR.png" />
<file href="scormcontent/assets/rituels%20collectifs.png" />
<file href="scormcontent/assets/lan2.png" />
<file href="scormcontent/assets/oddT2V/lan2.png" />
<file href="scormcontent/assets/REU.png" />
<file href="scormcontent/assets/ack.png" />
<file href="scormcontent/assets/r8HZyi/rituels.png" />
<file href="scormcontent/assets/FR%20RITUELS.pdf" />

      <file href="scormcontent/locales/en.js" />

    </resource>
  </resources>
</manifest>

=== zyllio/scorm-content/webstore/imsmanifest.xml
<?xml version="1.0" standalone="no" ?>
<manifest identifier="__ngGnH57sNCYHfic7Vodn8Yaj5qldVFggM-hsoA" version="1.3"
  xmlns="http://www.imsglobal.org/xsd/imscp_v1p1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_v1p3"
  xmlns:adlseq="http://www.adlnet.org/xsd/adlseq_v1p3"
  xmlns:imsss="http://www.imsglobal.org/xsd/imsss"
  xsi:schemaLocation="http://www.imsglobal.org/xsd/imscp_v1p1 imscp_v1p1.xsd
                      http://www.adlnet.org/xsd/adlcp_v1p3 adlcp_v1p3.xsd
                      http://www.adlnet.org/xsd/adlseq_v1p3 adlseq_v1p3.xsd
                      http://www.imsglobal.org/xsd/imsss imsss_v1p0.xsd">
  <metadata>
    <schema>ADL SCORM</schema>
    <schemaversion>2004 4th Edition</schemaversion>
    <adlcp:location>metadata.xml</adlcp:location>   
  </metadata>
  <organizations default="B0">
    <organization identifier="B0" adlseq:objectivesGlobalToSystem="false">
      <title>FR- WEBSTORE #1 - Bien démarrer !</title>
      <item identifier="i1" identifierref="r1" isvisible="true">
        <title>FR- WEBSTORE #1 - Bien démarrer !</title>
        <adlcp:dataFromLMS>eyJjcHYiOiJnZ00taHNvQSIsInJsZCI6ZmFsc2V9</adlcp:dataFromLMS>
        <imsss:sequencing>
          <imsss:deliveryControls tracked="true" completionSetByContent="true" objectiveSetByContent="true"/>
        </imsss:sequencing>
      </item>
      <metadata>
        <adlcp:location>metadata.xml</adlcp:location>
      </metadata>
      <imsss:sequencing>
        <imsss:controlMode choice="true" flow="true"/>
      </imsss:sequencing>
    </organization>
  </organizations>
  <resources>
    <resource identifier="r1" type="webcontent" adlcp:scormType="sco" href="scormdriver/indexAPI.html">
      <!-- SCORMDRIVER STUFF -->
      <file href="scormdriver/indexAPI.html" />
      <file href="scormdriver/preloadIntegrity.js" />
      <file href="scormdriver/driverOptions.js" />
      <file href="scormdriver/AICCComm.html" />
      <file href="scormdriver/auto-scripts/AutoBookmark.js" />
      <file href="scormdriver/auto-scripts/AutoCompleteSCO.js" />
      <file href="scormdriver/auto-scripts/CourseExit.js" />
      <file href="scormdriver/blank.html" />
      <file href="scormdriver/goodbye.html" />
      <file href="scormdriver/scormdriver.js" />
      <file href="scormdriver/browsersniff.js" />

      <!-- RUNTIME COMMON STUFF -->
      <file href="scormcontent/index.html" />

      
        <file href="scormcontent/lib/fonts/icomoon.ttf"/>
        <file href="scormcontent/lib/fonts/icomoon.woff"/>

        <file href="scormcontent/lib/icomoon.css"/>
        <file href="scormcontent/lib/player-0.0.11.min.js"/>
        <file href="scormcontent/lib/lzwcompress.js"/>
      

      <!-- FRONTEND BUNDLE ASSETS -->
      <file href="scormcontent/lib/rise/5d5a7671.js" />
<file href="scormcontent/lib/rise/fa74d7f1.css" />
<file href="scormcontent/lib/rise/ede5dd04.js" />
<file href="scormcontent/lib/rise/1cf4b6e0.css" />
<file href="scormcontent/lib/rise/a41cfcfc.js" />
<file href="scormcontent/lib/rise/254e83dc.js" />
<file href="scormcontent/lib/rise/c82cca6a.js" />
<file href="scormcontent/lib/rise/40b4cf18.js" />
<file href="scormcontent/lib/rise/b2cebec4.js" />
<file href="scormcontent/lib/rise/70fd6e03.js" />
<file href="scormcontent/lib/rise/48ed4c70.js" />
<file href="scormcontent/lib/rise/0bcec83e.js" />
<file href="scormcontent/lib/rise/bd8404c0.js" />
<file href="scormcontent/lib/mondrian/entry.js" />
<file href="scormcontent/lib/mondrian/ab103845.js" />
<file href="scormcontent/lib/mondrian/1a68f054.js" />
<file href="scormcontent/lib/mondrian/03ab2a8e.js" />
<file href="scormcontent/lib/mondrian/daeabcf0.js" />
<file href="scormcontent/lib/mondrian/45d26a13.js" />
<file href="scormcontent/lib/mondrian/09e37aee.js" />
<file href="scormcontent/lib/mondrian/196251cf.js" />
<file href="scormcontent/lib/sandbox/sandbox.html" />
<file href="scormcontent/lib/sandbox/b8fc6988.js" />
<file href="scormcontent/lib/sandbox/4adfab46.css" />


      <!-- RUNTIME CONTENT STUFF -->
      <file href="scormcontent/lib/fonts/Lato2-Regular.woff" />
<file href="scormcontent/lib/fonts/Lato2-Light.woff" />
<file href="scormcontent/lib/fonts/Lato2-Italic.woff" />
<file href="scormcontent/lib/fonts/Lato2-Bold.woff" />
<file href="scormcontent/lib/fonts/Lato2-Black.woff" />
<file href="scormcontent/lib/fonts/Merriweather-Black.woff" />
<file href="scormcontent/lib/fonts/Merriweather-Italic.woff" />
<file href="scormcontent/lib/fonts/Merriweather-Bold.woff" />
<file href="scormcontent/lib/fonts/Merriweather-Regular.woff" />
<file href="scormcontent/lib/fonts/Merriweather-Light.woff" />
<file href="scormcontent/assets/jGFlpDKW8wepF03E.jpg" />
<file href="scormcontent/assets/test%20fond.png" />
<file href="scormcontent/assets/look.png" />
<file href="scormcontent/assets/passer%20commande.png" />
<file href="scormcontent/assets/suivre%20etat%20commandes.png" />
<file href="scormcontent/assets/demandess.png" />
<file href="scormcontent/assets/pL3pmy/test%20fond.png" />
<file href="scormcontent/assets/connexionn.jpg" />
<file href="scormcontent/assets/connexion%20webstore.jpg" />
<file href="scormcontent/assets/4fHQzf/test%20fond.png" />
<file href="scormcontent/assets/test%20page%20d%27accueil.jpg" />
<file href="scormcontent/assets/langue.png" />
<file href="scormcontent/assets/Mes%20commandes.jpg" />
<file href="scormcontent/assets/menu%20famille.jpg" />
<file href="scormcontent/assets/panier.jpg" />
<file href="scormcontent/assets/d%C3%A9connexion.jpg" />
<file href="scormcontent/assets/mon%20magasin.jpg" />
<file href="scormcontent/assets/slider.jpg" />
<file href="scormcontent/assets/barre%20de%20recherche%20filtre.jpg" />
<file href="scormcontent/assets/BOPgpCUEiyJXUKw8.png" />

      <file href="scormcontent/locales/en.js" />

    </resource>
  </resources>
</manifest>

=== zyllio/scorm-content/manager-training/imsmanifest.xml
<?xml version="1.0" standalone="no" ?>
<manifest identifier="gi0w43r5S9yP-ARGUO297EvfCrX0UOeCRE0n4o5d" version="1.3"
  xmlns="http://www.imsglobal.org/xsd/imscp_v1p1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_v1p3"
  xmlns:adlseq="http://www.adlnet.org/xsd/adlseq_v1p3"
  xmlns:imsss="http://www.imsglobal.org/xsd/imsss"
  xsi:schemaLocation="http://www.imsglobal.org/xsd/imscp_v1p1 imscp_v1p1.xsd
                      http://www.adlnet.org/xsd/adlcp_v1p3 adlcp_v1p3.xsd
                      http://www.adlnet.org/xsd/adlseq_v1p3 adlseq_v1p3.xsd
                      http://www.imsglobal.org/xsd/imsss imsss_v1p0.xsd">
  <metadata>
    <schema>ADL SCORM</schema>
    <schemaversion>2004 3rd Edition</schemaversion>
    <adlcp:location>metadata.xml</adlcp:location>
  </metadata>
  <organizations default="B0">
    <organization identifier="B0" adlseq:objectivesGlobalToSystem="false">
      <title>New Manager Training</title>
      <item identifier="i1" identifierref="r1" isvisible="true">
        <title>New Manager Training</title>
        <adlcp:dataFromLMS>eyJjcHYiOiJSRTBuNG81ZCIsInJsZCI6ZmFsc2V9</adlcp:dataFromLMS>
        <imsss:sequencing>
          <imsss:deliveryControls tracked="true" completionSetByContent="true" objectiveSetByContent="true"/>
        </imsss:sequencing>
      </item>
      <metadata>
        <adlcp:location>metadata.xml</adlcp:location>
      </metadata>
      <imsss:sequencing>
        <imsss:controlMode choice="true" flow="true"/>
      </imsss:sequencing>
    </organization>
  </organizations>
  <resources>
    <resource identifier="r1" type="webcontent" adlcp:scormType="sco" href="scormdriver/indexAPI.html">
      <!-- SCORMDRIVER STUFF -->
      <file href="scormdriver/indexAPI.html" />
      <file href="scormdriver/preloadIntegrity.js" />
      <file href="scormdriver/driverOptions.js" />
      <file href="scormdriver/AICCComm.html" />
      <file href="scormdriver/auto-scripts/AutoBookmark.js" />
      <file href="scormdriver/auto-scripts/AutoCompleteSCO.js" />
      <file href="scormdriver/auto-scripts/CourseExit.js" />
      <file href="scormdriver/blank.html" />
      <file href="scormdriver/goodbye.html" />
      <file href="scormdriver/scormdriver.js" />
      <file href="scormdriver/browsersniff.js" />

      <!-- RUNTIME COMMON STUFF -->
      <file href="scormcontent/index.html" />

      
        <file href="scormcontent/lib/fonts/icomoon.ttf"/>
        <file href="scormcontent/lib/fonts/icomoon.woff"/>

        <file href="scormcontent/lib/icomoon.css"/>
        <file href="scormcontent/lib/player-0.0.11.min.js"/>
        <file href="scormcontent/lib/lzwcompress.js"/>
      

      <!-- FRONTEND BUNDLE ASSETS -->
      <file href="scormcontent/lib/rise/6b7684e3.js" />
<file href="scormcontent/lib/rise/b7e6275d.css" />
<file href="scormcontent/lib/rise/6c3dba4a.js" />
<file href="scormcontent/lib/rise/391be162.css" />
<file href="scormcontent/lib/rise/f033e23f.js" />
<file href="scormcontent/lib/rise/5ce3f37c.js" />
<file href="scormcontent/lib/rise/e8c73cc3.js" />
<file href="scormcontent/lib/rise/dbd76bf1.js" />
<file href="scormcontent/lib/rise/3c4d17f3.js" />
<file href="scormcontent/lib/mondrian/entry.js" />
<file href="scormcontent/lib/mondrian/cb77b9e0.js" />
<file href="scormcontent/lib/mondrian/5ac402cf.js" />
<file href="scormcontent/lib/mondrian/215fe725.js" />
<file href="scormcontent/lib/mondrian/c16e7dd3.js" />
<file href="scormcontent/lib/mondrian/5ebb90af.js" />
<file href="scormcontent/lib/mondrian/825dd797.js" />
<file href="scormcontent/lib/mondrian/beccd965.js" />
<file href="scormcontent/lib/mondrian/56ae9b9c.js" />


      <!-- RUNTIME CONTENT STUFF -->
      <file href="scormcontent/lib/fonts/Lato-Black.woff" />
<file href="scormcontent/lib/fonts/Lato-Italic.woff" />
<file href="scormcontent/lib/fonts/Lato-Bold.woff" />
<file href="scormcontent/lib/fonts/Lato-Regular.woff" />
<file href="scormcontent/lib/fonts/Lato-Light.woff" />
<file href="scormcontent/lib/fonts/Merriweather-Black.woff" />
<file href="scormcontent/lib/fonts/Merriweather-Italic.woff" />
<file href="scormcontent/lib/fonts/Merriweather-Bold.woff" />
<file href="scormcontent/lib/fonts/Merriweather-Regular.woff" />
<file href="scormcontent/lib/fonts/Merriweather-Light.woff" />
<file href="scormcontent/assets/small.png" />
<file href="scormcontent/assets/ri4xqT1RTWcNLa7F.jpg" />
<file href="scormcontent/assets/stock-image.png" />
<file href="scormcontent/assets/X-_noprocess_8636603.jpg" />
<file href="scormcontent/assets/stock-image.jpg" />
<file href="scormcontent/assets/13hsx9/stock-image.jpg" />
<file href="scormcontent/assets/57iBKb/quote_background.jpg" />
<file href="scormcontent/assets/pztwOP/stock-image.jpg" />
<file href="scormcontent/assets/wkyDIi/mountains.jpg" />
<file href="scormcontent/assets/L_yHhK/stock-image.jpg" />
<file href="scormcontent/assets/iYQFXU/stock-image.jpg" />
<file href="scormcontent/assets/bDR81P/stock-image.jpg" />
<file href="scormcontent/assets/RlJ6aN/stock-image.jpg" />
<file href="scormcontent/assets/JUdVok/stock-image.jpg" />
<file href="scormcontent/assets/X-_noprocess_teamphoto.jpg" />
<file href="scormcontent/assets/X-_noprocess_disagreements.jpg" />
<file href="scormcontent/assets/X-_noprocess_meeting.jpg" />
<file href="scormcontent/assets/X-_noprocess_employee.jpg" />
<file href="scormcontent/assets/eh0HZ_I5kNhWgRF7-stock-image.jpg" />
<file href="scormcontent/assets/67f7trmlkpH-zyTK-stock-image.jpg" />
<file href="scormcontent/assets/X-_noprocess_7491556.jpg" />
<file href="scormcontent/assets/agency.jpg" />
<file href="scormcontent/assets/SWQYX0/stock-image.jpg" />
<file href="scormcontent/assets/X-_noprocess_coaching.jpg" />
<file href="scormcontent/assets/X-_noprocess_newmanagercoachingquiz.jpg" />
<file href="scormcontent/assets/kuO0nAooM3-Asy_F_107_full.png" />
<file href="scormcontent/assets/l7QLybhUIC0wTWOT_78_full.png" />
<file href="scormcontent/assets/mZF2cjSr-3YsU8Q__141_full.png" />
<file href="scormcontent/assets/p3qQojsBv-wg62Cg_123_full.png" />
<file href="scormcontent/assets/9EaElT33ryWbyVqJ_77_full.png" />
<file href="scormcontent/assets/0yc8-hHdgcerDNjb_143_full.png" />
<file href="scormcontent/assets/RfvI7kVjAxSFl2Wu_95_full.png" />
<file href="scormcontent/assets/zfhB-aeR-1FEMEz0_87_full.png" />
<file href="scormcontent/assets/P6LxkwQUwDzLkbFU_120_full.png" />
<file href="scormcontent/assets/1hzwLpP7wI0XUY_0_81_full.png" />
<file href="scormcontent/assets/X5CuN7N9fEPdcnD3_79_full.png" />
<file href="scormcontent/assets/4G1RWlft1mZKUZRB_140_full.png" />

      <file href="scormcontent/locales/und.js" />

    </resource>
  </resources>
</manifest>
